---
# tasks file for set_kubeconfigj
- name: copy config for k8s
  ansible.builtin.copy:
    src: "{{ kubeconfig }}"
    dest: "{{ ansible_env.TMPDIR | default('/tmp') }}"
    mode: "0644"

- name: copy certs for k8s
  ansible.builtin.copy:
    src: "{{ kubecerts_dir }}"
    dest: "{{ ansible_env.TMPDIR | default('/tmp') }}"
    mode: "0644"
  when:
    - kubecerts_dir is defined