---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: set_kubeconfig
    - role: ingress-nginx
      tags: ingress-nginx
    - role: metallb
      tags: metallb
    - role: rm_kubeconfig