---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: set_kubeconfig
      tags:
        - k8tz
        - ingress
        - external-dns
        - ceph-operator
        - ceph-cluster
    - role: k8tz
      tags:
        - k8tz
    - role: ingress-nginx
      tags:
        - ingress
    - role: metallb
      tags:
        - ingress
    - role: external-dns
      tags:
        - external-dns
    - role: ceph-operator
      tags:
        - ceph-operator
    - role: ceph-cluster
      tags:
        - ceph-cluster
    - role: rm_kubeconfig
      tags:
        - k8tz
        - ingress
        - external-dns
        - ceph-operator
        - ceph-cluster