---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: set_kubeconfig
      tags:
        - ingress
        - ceph-operator
        - ceph-cluster
    - role: ingress-nginx
      tags:
        - ingress
    - role: metallb
      tags:
        - ingress
    - role: ceph-operator
      tags:
        - ceph-operator
    - role: ceph-cluster
      tags:
        - ceph-cluster
    - role: rm_kubeconfig
      tags:
        - ingress
        - ceph-operator
        - ceph-cluster