---
- hosts: ha_nfs
  gather_facts: false
  roles:
    - role: setup-hosts
      terraform_output_path: "{{ terraform_file_path }}"
      # when:
      #   - terraform_outputs_path is defined

    - role: initRHEL
      install_pkgs:
        - kmod-drbd9x
        - drbd9x-utils
        - firewalld
        - kernel-devel
        - zfs
        # - cryptsetup
        # - lvm2
      repos: "epel,elrepo"
      modprobes:
        - drbd
        - zfs

    # - role: setup-luks
    #   luksname: "cryptolvm"
    #   luksdevice: "/dev/sdb"
    #   lukspassphrase: "cryptolvm"

    - role: setup-drbd
      port: "{{ drbd_port }}"
      resources: "{{ drbd_resources }}"

    - role: ondrejhome.ha-cluster-pacemaker
      cluster_name: "ha-cluster"
      cluster_user_pass: "almalinux"
      cluster_firewall: true
      cluster_configure_fence_xvm: false
      cluster_configure_fence_kdump: true
      cluster_property:
        - name: "stonith-enabled"
          value: false
        - name: no-quorum-policy
          value: ignore
      cluster_resource:
        # - name: "drbd_r0"
        #   resource_class: "ocf"
        #   resource_type: "ocf:linbit:drbd"
        #   options: "drbd_resource=r0 op monitor interval=10s promotable monitor interval=30s meta promotable-max=1 promotable-node-max=1 clone-max=2 clone-node-max=1 notify=true"

        - name: VirtualIP
          resource_class: "ocf"
          resource_type: "ocf:heartbeat:IPaddr2"
          options: "ip=10.150.10.100 cidr_netmask=24 nic=enp5s0 op monitor interval=10s --group DRBD-group"

        - name: "DRBD-mount"
          resource_class: "ocf"
          resource_type: "ocf:heartbeat:Filesystem"
          options: "device=/dev/drbd0 directory=/drbd fstype=ext4 op start timeout=60s on-fail=restart op stop timeout=60s op monitor interval=10s timeout=60s on-fail=restart --group DRBD-group"

        - name: NFS-daemon
          resource_class: "ocf"
          resource_type: "systemd:nfs-server"
          options: "op start timeout=20s on-fail=restart op stop timeout=20s op monitor interval=10s timeout=10s on-fail=restart start-delay=20s --group DRBD-group"

        - name: NFS-exportfs
          resource_class: "ocf"
          resource_type: "ocf:heartbeat:exportfs"
          options: "clientspec=10.150.10.0/24 options=rw,async,no_root_squash,no_subtree_check directory=/drbd fsid=root --group DRBD-group"

    # - role: geerlingguy.nfs
