---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: debug tmp path
      debug:
        msg: "{{ ansible_env.TMPDIR | default('/tmp') }}"
    - name: copy certs for k8s
      ansible.builtin.copy:
        src: ./.kube/kubernetes
        dest: "{{ ansible_env.TMPDIR | default('/tmp') }}"
        mode: "0644"
    - name: Create Kasten-io namespace.
      kubernetes.core.k8s:
        name: helm-tutorial
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: ./.kube/admin.kubeconfig
        context: "development"
    - name: Add Stable helm repository.
      kubernetes.core.helm_repository:
        name: stable
        repo_url: "https://charts.helm.sh/stable"
    - name: Add prometheus-community repository.
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"
    - name: Deploy latest version of Grafana chart inside monitoring namespace with values
      kubernetes.core.helm:
        name: stable
        chart_ref: prometheus-community/prometheus
        release_namespace: helm-tutorial
        state: present
        kubeconfig: ./.kube/admin.kubeconfig
        context: "development"
    - name: remove certs for k8s
      ansible.builtin.file:
        path: "{{ ansible_env.TMPDIR | default('/tmp') }}/kubernetes"
        state: absent