---
# tasks file for ./roles/initRHEL
- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: "Asia/Tokyo"

- name: Import GPG key for zfs-release
  ansible.builtin.rpm_key:
    state: present
    key: https://raw.githubusercontent.com/zfsonlinux/zfsonlinux.github.com/master/zfs-release/RPM-GPG-KEY-openzfs-key2

- name: Install extra repo
  ansible.builtin.dnf:
    name:
      - elrepo-release
      - epel-release
      - https://zfsonlinux.org/epel/zfs-release-2-3.el9.noarch.rpm
    state: latest

- name: Install some packages
  ansible.builtin.dnf:
    name:
      - kmod-drbd9x
      - zfs
    state: latest
    enablerepo: elrepo,zfs

- name: Load drbd
  community.general.modprobe:
    name: drbd
    persistent: present

- name: Load zfs
  community.general.modprobe:
    name: zfs
    persistent: present

- name: Reboot (timeout 5minitus)
  ansible.builtin.reboot:
    reboot_timeout: 600