---
- name: Add metallb chart repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"

- name: Deploy latest version of metallb
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"

- name: Apply metallb config to the cluster.
  kubernetes.core.k8s:
    state: present
    src: "roles/metallb/files/{{ stage }}.yml"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"