---
# tasks file for metallb
- name: copy values.yml
  ansible.builtin.copy:
    src: "{{ stage }}.yml"
    dest: "{{ ansible_env.TMPDIR | default('/tmp') }}"
    mode: "0644"

- name: Add metallb chart repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"

- name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"

- name: Apply metallb config to the cluster.
  kubernetes.core.k8s:
    state: present
    src: "{{ stage }}.yml"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"

- name: remove values.yml
  ansible.builtin.file:
    path: "{{ ansible_env.TMPDIR | default('/tmp') }}/{{ stage }}.yml"
    state: absent