# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  collection-community-general = {
    pname = "collection-community-general";
    version = "7.4.0";
    src = fetchurl {
      url = "https://galaxy.ansible.com/download/community-general-7.4.0.tar.gz";
      sha256 = "sha256-7awKnluF+YerycTcHeB3ZCCpoPhLVcOzIxw++fFz0d0=";
    };
  };
  collection-kubernetes-core = {
    pname = "collection-kubernetes-core";
    version = "2.4.0";
    src = fetchurl {
      url = "https://galaxy.ansible.com/download/kubernetes-core-2.4.0.tar.gz";
      sha256 = "sha256-NxNYCIb4+bUJ9c4JzuNgZ1zkWxcOU2Mdkwe3bR3Nvyw=";
    };
  };
  role-ansible-role-nfs = {
    pname = "role-ansible-role-nfs";
    version = "2.0.0";
    src = fetchFromGitHub ({
      owner = "geerlingguy";
      repo = "ansible-role-nfs";
      rev = "2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-OFVwlSBdHAoa3F5QATzDUzP7jhlq1cc0uNe5HfUYz6w=";
    });
    aname = "geerlingguy.nfs";
  };
  role-ha-cluster-pacemaker = {
    pname = "role-ha-cluster-pacemaker";
    version = "41.0.0";
    src = fetchFromGitHub ({
      owner = "OndrejHome";
      repo = "ansible.ha-cluster-pacemaker";
      rev = "41.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-EDOpLVELfdxVriVhn26cI/yNe3SDNJWd9IhqqUvXaT0=";
    });
    aname = "ondrejhome.ha-cluster-pacemaker";
  };
  role-pcs-module-2 = {
    pname = "role-pcs-module-2";
    version = "28.0.0";
    src = fetchFromGitHub ({
      owner = "OndrejHome";
      repo = "ansible.pcs-modules-2";
      rev = "28.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-K5uGz/ylKlb+gNGL7J3N4AqRzTrDiAOn8wXZwC8Gzik=";
    });
    aname = "ondrejhome.pcs-modules-2";
  };
}
