---
# tasks file for ./roles/setup-lvm-on-drbd
- name: Create a volume group on top of /dev/drbd0
  community.general.lvg:
    vg: VolGroupNFS
    pvs: /dev/drbd0

- name: Resize the logical volume to % of VG
  community.general.lvol:
    vg: VolGroupNFS
    lv: lvolnfs
    size: 100%VG