---
- name: Add ingress-nginx chart repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"
- name: Deploy latest version of ingress-nginx chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    values_files:
      - roles/ingress-nginx/files/values.yml
    release_namespace: ingress-nginx
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"