---
# tasks file for ingress-nginx
- name: Add ingress-nginx chart repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"
- name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ stage }}"