---
# tasks file for roles/setup-drbd
- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    port: "{{ port }}/tcp"
    permanent: true
    state: enabled

- name: Set drbd resource
  ansible.builtin.set_fact:
    _resources: "{{ resources }}"
    port: "{{ port }}"
  run_once: yes

- name: Set drbd config
  become: yes
  ansible.builtin.template:
    src: res.j2
    dest: /etc/drbd.d/r0.res
    owner: root
    group: root
    mode: 0644

- name: Create-md
  ansible.builtin.command: drbdadm create-md r0
  ignore_errors: True

- name: Up drbd
  ansible.builtin.command: drbdadm up r0

- name: Make drbd primary on an instance set to primary
  ansible.builtin.command: drbdadm primary r0 --force
  when: "{{ drbd_primary | default(false) }}"
