---
# tasks file for roles/setup-drbd
- name: Set drbd resource
  ansible.builtin.set_fact:
    _resource: "{{ resource }}"
  run_once: yes

- debug:
    msg: "{{ _resource }}"

- name: Set drbd config
  become: yes
  ansible.builtin.template:
    src: res.j2
    dest: /etc/drbd.d/r0.res
    owner: root
    group: root
    mode: 0644
