---
all:
  vars:
    stage: development
  children:
    kubectl:
      vars:
        kubeconfig: "{{ playbook_dir }}/.kube/admin.kubeconfig"
        kubecerts_dir: "{{ playbook_dir }}/.kube/kubernetes"
        metallb_addresses: "10.150.10.200-10.150.10.250"
      hosts:
        localhost:
    ha_nfs:
      vars:
        remote_user: root
        terraform_file_path: "{{ playbook_dir }}/../nixos-k8s-config/terraform/nfs/development.json"
        drbd_port: 7789
        drbd_resources:
          - target: "nfs1"
            id: 0
            address: "10.150.10.70"
            meta_disk: "internal"
            disks:
              - "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_lxd_nfs"
          - target: "nfs2"
            id: 1
            address: "10.150.10.71"
            meta_disk: "internal"
            disks:
              - "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_lxd_nfs"
      hosts:
        nfs1:
        nfs2:
